FROM {{ common_docker_image }}
MAINTAINER KIYOHIRO ADACHI <kiyoad@da2.so-net.ne.jp>

RUN \
  apt-get install -qy nova-api nova-cert nova-conductor nova-consoleauth nova-novncproxy nova-scheduler && \
  rm -rf /var/lib/nova/nova.sqlite && \
  rm -rf /var/lib/apt/lists/*

ADD service_launcher.sh /usr/local/bin/service_launcher.sh
RUN chmod 0755 /usr/local/bin/service_launcher.sh
ADD monit_nova-api.conf /etc/monit/conf.d/nova-api.conf
ADD monit_nova-cert.conf /etc/monit/conf.d/nova-cert.conf
ADD monit_nova-consoleauth.conf /etc/monit/conf.d/nova-consoleauth.conf
ADD monit_nova-scheduler.conf /etc/monit/conf.d/nova-scheduler.conf
ADD monit_nova-conductor.conf /etc/monit/conf.d/nova-conductor.conf
ADD monit_nova-novncproxy.conf /etc/monit/conf.d/nova-novncproxy.conf
ADD monit_openssh-server.conf /etc/monit/conf.d/openssh-server.conf
ADD sshd_config /etc/ssh/sshd_config

CMD [ "service_launcher.sh" ]
