FROM {{ common_docker_image }}
MAINTAINER KIYOHIRO ADACHI <kiyoad@da2.so-net.ne.jp>

RUN \
  apt-get install -qy apache2 memcached libapache2-mod-wsgi openstack-dashboard && \
  apt-get remove -qy --purge openstack-dashboard-ubuntu-theme && \
  rm -rf /var/lib/apt/lists/*

ADD service_launcher.sh /usr/local/bin/service_launcher.sh
RUN chmod 0755 /usr/local/bin/service_launcher.sh
ADD monit_apache2.conf /etc/monit/conf.d/apache2.conf
ADD monit_memcached.conf /etc/monit/conf.d/memcached.conf

CMD [ "service_launcher.sh" ]
