FROM {{ common_docker_image }}
MAINTAINER KIYOHIRO ADACHI <kiyoad@da2.so-net.ne.jp>

RUN \
  apt-get install -qy cinder-api cinder-scheduler && \
  rm -rf /var/lib/cinder/cinder.sqlite && \
  rm -rf /var/lib/apt/lists/*

ADD service_launcher.sh /usr/local/bin/service_launcher.sh
RUN chmod 0755 /usr/local/bin/service_launcher.sh
ADD monit_cinder-api.conf /etc/monit/conf.d/cinder-api.conf
ADD monit_cinder-scheduler.conf /etc/monit/conf.d/cinder-scheduler.conf
ADD monit_openssh-server.conf /etc/monit/conf.d/openssh-server.conf
ADD sshd_config /etc/ssh/sshd_config

CMD [ "service_launcher.sh" ]
