FROM {{ common_docker_image }}
MAINTAINER KIYOHIRO ADACHI <kiyoad@da2.so-net.ne.jp>

RUN \
  apt-get install -qy glance && \
  rm -rf /var/lib/glance/glance.sqlite && \
  rm -rf /var/lib/apt/lists/*

ADD service_launcher.sh /usr/local/bin/service_launcher.sh
RUN chmod 0755 /usr/local/bin/service_launcher.sh
ADD monit_glance-api.conf /etc/monit/conf.d/glance-api.conf
ADD monit_glance-registry.conf /etc/monit/conf.d/glance-registry.conf

CMD [ "service_launcher.sh" ]
